# Crops each headshot to a square (top-anchored), resizes to 640px, and embeds
# (plus optional 480x600 profile photos, see $photosLarge below)
# them as base64 data URIs into index.html between the PHOTOS-START/END markers.
# Re-run any time you change a photo. Map of roster key -> source file:
$photos = [ordered]@{
  jacob    = 'C:\Users\jacob\Downloads\_T3A7156.jpg'
  megan    = 'C:\Users\jacob\Downloads\_T3A7205.jpg'
  lindsay  = 'C:\Users\jacob\Downloads\_T3A7272.jpg'
  vidhi    = 'C:\Users\jacob\Downloads\_T3A7172.jpg'
  annalise = 'C:\Users\jacob\Downloads\_T3A7303.jpg'
  nina     = 'C:\Users\jacob\Downloads\Nikolina Dimitrijevic Portrait_Willis_20260728_Vangel_T3A7240.jpg'
  jada     = 'C:\Users\jacob\Downloads\_T3A7337.jpg'
  brianna  = 'C:\Users\jacob\Downloads\IMG_1372.jpeg'
}
# Larger, different photos for the profile dialog (4:5 portrait, 480x600).
# Key must match the roster's `photoLarge` field, e.g. photoLarge:'jacob_large'.
# Leave an entry out and the dialog falls back to the square headshot.
$photosLarge = [ordered]@{
  # jacob_large = 'C:\Users\jacob\Downloads\jacob-project.jpg'
}

Add-Type -AssemblyName System.Drawing
$size = 640   # 2x the ~300px the profile dialog shows, so headshots stay sharp on retina
$entries = @()

# ($key, $src, $outW, $outH) for every photo: squares first, then large portraits
$jobs = @()
foreach ($key in $photos.Keys)      { $jobs += ,@($key, $photos[$key], $size, $size) }
foreach ($key in $photosLarge.Keys) { $jobs += ,@($key, $photosLarge[$key], 480, 600) }

foreach ($job in $jobs) {
  $key = $job[0]; $src = $job[1]; $outW = $job[2]; $outH = $job[3]
  if (-not (Test-Path $src)) { Write-Warning "missing: $src"; continue }
  $img = [System.Drawing.Image]::FromFile($src)
  try {
    # top-anchored crop to the output aspect ratio: faces sit in the upper part
    $ratio = $outW / $outH
    if ($img.Width / $img.Height -gt $ratio) { $ch = $img.Height; $cw = [int]($ch * $ratio) }
    else                                     { $cw = $img.Width;  $ch = [int]($cw / $ratio) }
    $y = [int]($img.Height * 0.02)
    if ($y + $ch -gt $img.Height) { $y = $img.Height - $ch }
    $x = [int](($img.Width - $cw) / 2)

    $bmp = New-Object System.Drawing.Bitmap $outW, $outH
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
    $srcRect = New-Object System.Drawing.Rectangle $x, $y, $cw, $ch
    $dstRect = New-Object System.Drawing.Rectangle 0, 0, $outW, $outH
    $g.DrawImage($img, $dstRect, $srcRect, [System.Drawing.GraphicsUnit]::Pixel)
    $g.Dispose()

    $codec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object { $_.MimeType -eq 'image/jpeg' }
    $ep = New-Object System.Drawing.Imaging.EncoderParameters 1
    $ep.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter([System.Drawing.Imaging.Encoder]::Quality, [long]82)
    $ms = New-Object System.IO.MemoryStream
    $bmp.Save($ms, $codec, $ep)
    $bmp.Dispose()

    $b64 = [Convert]::ToBase64String($ms.ToArray())
    $ms.Dispose()
    $entries += "  ${key}:'data:image/jpeg;base64,$b64'"
    Write-Host ("{0}: {1:n0} KB embedded" -f $key, ($b64.Length * 3 / 4 / 1KB))
  } finally {
    $img.Dispose()
  }
}

$block = "// PHOTOS-START - generated by embed-photos.ps1, do not hand-edit`nconst PHOTOS = {`n" +
         ($entries -join ",`n") + "`n};`n// PHOTOS-END"

$path = Join-Path $PSScriptRoot 'index.html'
$html = [System.IO.File]::ReadAllText($path)
$pattern = '(?s)// PHOTOS-START.*?// PHOTOS-END'
if ($html -notmatch $pattern) { throw 'PHOTOS markers not found in index.html' }
$html = [regex]::Replace($html, $pattern, $block.Replace('$', '$$'))
[System.IO.File]::WriteAllText($path, $html, (New-Object System.Text.UTF8Encoding $false))
Write-Host "index.html updated with $($entries.Count) photos"
